# Scoreboard
scoreboard:
  title: "&e&lTESTBOARD"
  scores:
    - "&aLine 1"
    - "&aLine 2"
    - "&aLine 3"
    - "&aLine 4"
    - "&aLine 5"
    - "&aLine 6"
    - "&aLine 7"
    - "&aLine 8"
    - "&aLine 9"
    - "&aLine 10"
