name: Deploy Maven Project to GitHub Packages

on:
  push:
    branches:
      - main

  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install --settings .github/settings.xml

    - name: Deploy to GitHub Packages
      run: mvn deploy -s .github/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        
